# -*- coding: utf-8 -*-
"""Dia_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14C9WBKCC02VzFNlXqxLoOXVLOxYwBy5X
"""

#Dia 1 - Identificando o Chá
#Link para o desafio: https://www.beecrowd.com.br/judge/pt/problems/view/2006


#Enunciado:
'''Degustação de chá às escuras é a habilidade de identificar um chá usando apenas seus sentidos do olfato e paladar.

Isto faz parte da Competição Ideal de Consumidores de Chá Puro (da sigla em inglês ICPC), que um programa de TV local está organizando.
Durante o show, um bule de chá completo é preparado e são entregues uma xícara de chá para cada um dos cinco competidores. Os participantes devem cheirar,
saborear e avaliar a amostra, de modo a identificar o tipo de chá, que pode ser: (1) o chá branco; (2) chá verde; (3) chá preto; ou (4) chá de ervas. No final,
as respostas são verificadas para determinar o número de suposições corretas.

Dado o tipo de chá real e as respostas fornecidas, determinar o número de participantes que receberam a resposta correta.

Entrada
A primeira linha contém um inteiro T representando o tipo de chá (1 ≤ T ≤ 4). A segunda linha contém cinco inteiros A, B, C, D e E,
que indica a resposta dada por cada competidor (1 ≤ A, B, C, D, E ≤ 4).

Saída
A saída contém um inteiro representando o número de concorrentes que obtiveram a resposta correta.'''


T = int(input())

# Entrada dos 5 valores utilizando map: inicialmente o input recebe uma string, então os elementos são seprados pelo espaço utilizando split,
# com o map é aplicado em cada elemento a função int para transforma-los em um valor inteiro, então é devolvindo para as variáveis.

c1, c2, c3, c4, c5 = map(int, input().split())

chas = [c1,c2,c3,c4,c5]

contador = 0

for c in chas:
  if T == c:
    contador +=1

print(contador, '\n')