# -*- coding: utf-8 -*-
"""dia_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10InqT55TNboTap2hHH9soQWnOQEv-gLc
"""

#Dia 2 - Criptografia
#Link para o desafio: https://www.beecrowd.com.br/judge/pt/problems/view/1024

#Enunciado:
'''
Solicitaram para que você construisse um programa simples de criptografia. Este programa deve possibilitar enviar mensagens codificadas sem que alguém consiga lê-las. O processo
é muito simples. São feitas três passadas em todo o texto.

Na primeira passada, somente caracteres que sejam letras minúsculas e maiúsculas devem ser deslocadas 3 posições para a direita, segundo a tabela ASCII: letra 'a' deve virar
letra 'd', letra 'y' deve virar caractere '|' e assim sucessivamente. Na segunda passada, a linha deverá ser invertida. Na terceira e última passada,
todo e qualquer caractere a partir da metade em diante (truncada) devem ser deslocados uma posição para a esquerda na tabela ASCII. Neste caso, 'b' vira 'a' e 'a' vira '`'.

Por exemplo, se a entrada for “Texto #3”, o primeiro processamento sobre esta entrada deverá produzir “Wh{wr #3”. O resultado do segundo processamento inverte os
caracteres e produz “3# rw{hW”. Por último, com o deslocamento dos caracteres
da metade em diante, o resultado final deve ser “3# rvzgV”.

Entrada
A entrada contém vários casos de teste. A primeira linha de cada caso de teste contém um inteiro N (1 ≤ N ≤ 1*104), indicando a quantidade de linhas que
o problema deve tratar. As N linhas contém cada uma delas M (1 ≤ M ≤ 1*103) caracteres.
'''


#Numero de linhas
N = int(input())

#Lista de linhas
listaL = []

#Auxiliar de input
aux = ''

for linha in range(0, N):
  aux = str(input())
  listaL.append(aux)

#lista da Primeira Passada
listaPrimeira = []
#linha em processo de crptografia
linhaCripto = ''
#Pirmeira Passada
for linha in listaL:
  for letra in linha:
    if letra.isalpha():
      linhaCripto += str(chr(ord(letra) + 3))
    if not letra.isalpha():
      linhaCripto += letra
  listaPrimeira.append(linhaCripto)
  linhaCripto = ''

#Lista da Segunda Passada
listaSegunda = []

#Segunda Passada
for palavra in listaPrimeira:
  listaSegunda.append(palavra[::-1])

#Lista da Terceira Passada
listaTerceira = []

#Metade da palavra
metadeTruncada = 0

#Controlador da metade
controladorM = 0

for palavra in listaSegunda:
  metadeTruncada = len(palavra) // 2
  controladorM = 0
  linhaCripto = ''
  for letra in palavra:
    if not (controladorM < metadeTruncada):
      linhaCripto += str(chr(ord(letra) - 1))
    else:
      linhaCripto += letra
      controladorM += 1
  listaTerceira.append(linhaCripto)


for palavra in listaTerceira:
  print(palavra.strip())